FROM golang:1.21-alpine AS builder

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the source code
COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -o /bot ./cmd/bot/main.go

# Create a minimal image
FROM alpine:latest

WORKDIR /app

COPY --from=builder /bot .
COPY .env .

# Run the application
CMD ["./bot"] 